models/contact.py
from utils.db import db

class Contact(db.Model):
    id = db.Column(db.Integer, primary_key=True)
    fullname = db.Column(db.String(100))
    email = db.Column(db.String(100))
    phone = db.Column(db.String(100))
    
    def __init__(self, fullname, email, phone):
        self.fullname = fullname
        self.email = email
        self.phone = phone

app.py
from flask import Flask
from routes.contacts import contacts
from utils.db import db
from config import DATABASE_CONNECTION_URI

app = Flask(__name__)

app.secret_key = "secret key"
app.config['SQLALCHEMY_DATABASE_URI'] = DATABASE_CONNECTION_URI
app.config['SQLALCHEMY_TRACK_MODIFICATIONS'] = False

db.init_app(app)

app.register_blueprint(contacts)

routes/contacts.py
from flask import Blueprint, render_template, request, redirect, url_for, flash
from models.contact import Contact
from utils.db import db

contacts = Blueprint('contacts', __name__)


@contacts.route('/')
def home():
    contacts = Contact.query.all()
    return render_template('index.html', contacts = contacts)

@contacts.route('/about')
def about():
    return render_template('about.html')

@contacts.route('/delete/<id>', methods=['POST', 'GET'])
def delete(id):
    contact = Contact.query.get(id)
    db.session.delete(contact)
    db.session.commit()
    flash("Contact deleted successfully!")
    return redirect(url_for('contacts.home'))

@contacts.route('/update/<id>', methods=['POST', 'GET'])
def update(id):
    contact = Contact.query.get(id)
    if request.method == 'POST':
        contact.fullname = request.form["fullname"]
        contact.email = request.form["email"]
        contact.phone = request.form["phone"]
        db.session.commit()
        flash("Contact updated successfully!")
        return redirect(url_for('contacts.home'))
    else:
        return render_template('update.html', contact = contact)

@contacts.route('/new', methods=['POST'])
def add_contact():
    print(request.form)
    fullname = request.form["fullname"]
    email = request.form["email"]
    phone = request.form["phone"]
    new_contact = Contact(fullname, email, phone)
    db.session.add(new_contact)
    db.session.commit()
    flash("Contact added successfully!")
    return redirect(url_for('contacts.home'))

templates/about.html
{% extends 'layout.html' %} 

{% block content %}

<div class="container p-4">

<h4 class="text-white">There is nothing here</h4>
<p class="text-white">Well... this is just a page with nothing inside of it, did you expected something here?</p>
</div>

{% endblock %}

templates/index.html
{% extends 'layout.html' %} 

{% block content %}

<div class="row">
  <div class="col-md-5">
    {% include('partials/_messages.html') %} 
    {% include('partials/_contactform.html') %}
  </div>

  <div class="col-md-7">
    <div>
      {% for contact in contacts %}

      <div class="card mb-1 text-white bg-dark">
        <div class="card-body">

          <div class="d-flex justify-content-between">

            <h5>{{contact.fullname}}</h5>
            <div>
              <a href="{{ url_for('contacts.update', id=contact.id) }}" class="btn btn-dark btn-sm rounded-2">Update</a>
              <a href="{{ url_for('contacts.delete', id=contact.id) }}" class="btn btn-dark btn-sm rounded-2">Delete</a>
            </div>
          </div>
          <p>{{contact.email}}</p>
          <p>{{contact.phone}}</p>
          </div>



          
      </div>

      {% endfor %}
    </div>
  </div>
</div>

{% endblock %}

templates/layout.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>Practice Flask and SQL Alchemy</title>

    <!-- Importación del CSS de bootstrap -->
    <link
      href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha2/dist/css/bootstrap.min.css"
      rel="stylesheet"
      integrity="sha384-aFq/bzH65dt+w6FI2ooMVUpc+21e0SRygnTpmBvdBgSdnuTN7QbdgL+OapgHtvPp"
      crossorigin="anonymous"
    />
  </head>
  <body class="bg-black">
    {% include('partials/_navbar.html') %}

    <div class="container p-2">
        
        {% block content %} 
        
        {% endblock %}

    </div>

    <!-- Importación del Javascript de bootstrap -->
    <script
      src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha2/dist/js/bootstrap.bundle.min.js"
      integrity="sha384-qKXV1j0HvMUeCBQ+QVp7JcfGl760yU08IQ+GpUo5hlbpg51QRiuqHAJz8+BrxE/N"
      crossorigin="anonymous"
    ></script>
  </body>
</html>

templates/partials/_contactform.html
<form
  action="/new"
  method="POST"
  enctype="multipart/form-data"
  class="card bg-dark text-light"
>
  <div class="card-body p-4">
    <div class="mb-2">
      <label for="fullname">Write your fullname:</label>
      <input
        type="text"
        name="fullname"
        placeholder="Write your fullname"
        class="form-control rounded-2 bg-dark border-0 text-white"
      />
    </div>
    <div class="mb-2">
      <label for="email">Write your email:</label>
      <input
        type="email"
        name="email"
        placeholder="Write your email"
        class="form-control rounded-2 bg-dark border-0 text-white"
      />
    </div>
    <div class="mb-2">
      <label for="phone">Write your phone:</label>
      <input
        type="text"
        name="phone"
        placeholder="Write your phone number"
        class="form-control rounded-2 bg-dark border-0 text-white"
      />
    </div>

    <input class="btn btn-secondary rounded-2 border-0" type="submit" name="submit" placeholder="Send" />
  </div>
</form>

templates/partials/_messages.html
{% with messages = get_flashed_messages() %}
  {% if messages %}
    {% for message in messages %}
      {{message}}
    {% endfor %}
  {% endif %}
{% endwith %}

templates/partials/_navbar.html
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
  <div class="container">
    <a class="navbar-brand" href="/">Flask Practice</a>
    <button
      class="navbar-toggler"
      type="button"
      data-bs-toggle="collapse"
      data-bs-target="#navbarNav"
      aria-controls="navbarNav"
      aria-expanded="false"
      aria-label="Toggle navigation"
    >
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarNav">
      <ul class="navbar-nav ms-auto">
        <li class="nav-item">
          <a href="/about" class="nav-link">About</a>
        </li>
      </ul>
    </div>
  </div>
</nav>

templates/update.html
{% extends 'layout.html' %}

{% block content %}

    <h1 class="text-white">Update</h1>

    <form action="/update/{{contact.id}}" method="POST" enctype="multipart/form-data">
        <input type="text" name="fullname" placeholder="Write your fullname" value="{{contact.fullname}}" />
        <input type="email" name="email" placeholder="Write your email" value="{{contact.email}}" />
        <input type="text" name="phone" placeholder="Write your phone number" value="{{contact.phone}}" />
        <input type="submit" name="submit" placeholder="Send" />
    </form>

</body>
</html>

{% endblock %}